title: "Nithese Kanna – Java Portfolio"
description: "Java Backend Developer | Spring Boot | Oracle | Hibernate"
baseurl: "" 
url: "https://your-github-username.github.io/nithese-portfolio"
theme: minima
