title: "Nithese Kanna – Java Portfolio"
description: "Java Backend Developer | Spring Boot | Oracle | Hibernate"
baseurl: "/nithese-portfolio"  # ✅ required for subfolder project
url: "https://nithesekanna.github.io"
theme: minima
markdown: kramdown
